// Regenerates web/difficulty.js: number of distinct solutions (equivalence classes)
// for every solvable set, used to order the Train page's "solve" deck.
//   node scripts/class-counts.js
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const web = path.join(__dirname, '..', 'web');
const ctx = { console };
vm.createContext(ctx);
for (const f of ['solutions.js', 'common.js']) {
  // Top-level const bindings don't become context properties; expose the ones we need.
  vm.runInContext(fs.readFileSync(path.join(web, f), 'utf8'), ctx, { filename: f });
}
vm.runInContext('this.__out = {}; for (const k of SOLVABLE_KEYS) __out[k] = solveClasses(k.split("-").map(Number)).length;', ctx);
const out = ctx.__out;
fs.writeFileSync(path.join(web, 'difficulty.js'),
  '// Generated by scripts/class-counts.js: distinct solutions per solvable set.\n' +
  `const CLASS_COUNT = ${JSON.stringify(out)};\n`);
console.log(Object.keys(out).length, 'sets');
