// Regenerates web/difficulty.js: for every solvable set, the number of distinct
// solutions (equivalence classes) and the total number of written forms across them.
// Used to filter and order the Train page's "solve" deck.
//   node scripts/class-counts.js
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const web = path.join(__dirname, '..', 'web');
const ctx = { console };
vm.createContext(ctx);
for (const f of ['solutions.js', 'common.js']) {
  // Top-level const bindings don't become context properties; expose the ones we need.
  vm.runInContext(fs.readFileSync(path.join(web, f), 'utf8'), ctx, { filename: f });
}
vm.runInContext(`this.__out = {}; this.__tot = {};
  for (const k of SOLVABLE_KEYS) {
    const cs = solveClasses(k.split('-').map(Number));
    __out[k] = cs.length;
    __tot[k] = cs.reduce((t, c) => t + c.forms.length, 0);
  }`, ctx);
const out = ctx.__out, tot = ctx.__tot;
fs.writeFileSync(path.join(web, 'difficulty.js'),
  '// Generated by scripts/class-counts.js: distinct solutions and total written forms per solvable set.\n' +
  `const CLASS_COUNT = ${JSON.stringify(out)};\n` +
  `const FORM_COUNT = ${JSON.stringify(tot)};\n`);
console.log(Object.keys(out).length, 'sets');
